name: Validate ARM Template

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-template:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Validate ARM Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: rg-template-validation
        template: "./AVD Workbook/deploy-avd-data-collection.json"
        parameters: "./AVD Workbook/deploy-avd-data-collection.parameters.json"
        deploymentMode: Validate
        
    - name: Test ARM Template Syntax
      run: |
        az deployment group validate \
          --resource-group rg-template-validation \
          --template-file "AVD Workbook/deploy-avd-data-collection.json" \
          --parameters "AVD Workbook/deploy-avd-data-collection.parameters.json"
          
    - name: Run Template Analysis
      run: |
        # Install ARM Template Toolkit
        Install-Module -Name arm-ttk -Force -Scope CurrentUser
        
        # Run ARM TTK tests
        Import-Module arm-ttk
        Test-AzTemplate -TemplatePath "./AVD Workbook/deploy-avd-data-collection.json"
      shell: pwsh
